name: "On PR"

on:
  pull_request:
    branches:
      - master
      - development

jobs:
  # Builds docker image but does not push it.
  build-server:
    uses: tagshelfsrl/github-actions/.github/workflows/docker-build-push-v2.yml
    secrets: inherit
    with:
      images: ${{github.repository}}
      file: docker/server/Dockerfile

  build-web:
    uses: tagshelfsrl/github-actions/.github/workflows/docker-build-push-v2.yml
    secrets: inherit
    with:
      images: ${{github.repository}}
      file: docker/ui/Dockerfile
