###############################################################################
# When a tag is pushed is the signal to actually push the container image with
# a tag that matches.
###############################################################################
name: "On Tag Pushed"

on:
  push:
    tags:
      - v*

jobs:
  push-server:
    uses: tagshelfsrl/github-actions/.github/workflows/docker-build-push-gcp.yml@v1.11.1
    secrets:
      host: us-east1-docker.pkg.dev
      workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      service_account: ${{ secrets.GCP_GITHUB_ACTIONS_SA }}
      build-args: |
        BUILD_TAG=${{github.ref_name}}
    with:
      push: true
      file: docker/server/Dockerfile
      images: |
        us-east1-docker.pkg.dev/tagshelf/tagshelfsrl/conductor-server

  push-web:
    uses: tagshelfsrl/github-actions/.github/workflows/docker-build-push-gcp.yml@v1.11.1
    secrets:
      host: us-east1-docker.pkg.dev
      workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
      service_account: ${{ secrets.GCP_GITHUB_ACTIONS_SA }}
      build-args: |
        BUILD_TAG=${{github.ref_name}}
    with:
      push: true
      file: docker/ui/Dockerfile
      images: |
        us-east1-docker.pkg.dev/tagshelf/tagshelfsrl/conductor-web
